#baseURL = "/"
baseURL = 'https://amitux.co.nz/test-git'
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Hugo Winston Theme"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
heading1Small = "42px"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-PMT1SN49E9"
  twitter_handle = "@Appaui1"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = true
  addFrame = true
  highlightColor = '#042A29'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#03A069"
  logo_img = "images/logo.svg"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
    
    [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = 2
    
  
