baseURL = 'https://amitux.co.nz/'
#baseURL = '/'
languageCode = 'en-us'
title = 'Amitabha Ghosh'
theme = "hugo-winston-theme"


[params]
  google_analytics_id = "G-PMT1SN49E9"
  twitter_handle = "@Appaui1"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = true
  addFrame = true
  highlightColor = '#042A29'
  logo_img = "images/logo.svg"
  link_color = "#0F00B8"
  featured_img_small = "240px"
  featured_img_large = "900px"

